version: "3.8"

services:
  client:
    container_name: nsf-prototype-client 
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - nsf-prototype

  server:
    container_name: nsf-prototype-server 
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes: 
      - ./server:/app
    ports:
      - "8443:8443"
    healthcheck:
      test: wget -qO- --no-verbose --tries=1 server:8000/health &> /dev/null || exit 1
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 1
    depends_on:
      - db
    networks:
      - nsf-prototype
  
  db:
    container_name: nsf-prototype-db
    build:
      context: ./db
      dockerfile: Dockerfile 
    restart: always
    environment:
      - POSTGRES_DB=nsf-prototype
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - nsf-prototype

networks:
  nsf-prototype:
    driver: bridge
