version: "3.8"

services:
  client:
    container_name: nsf-prototype-client 
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - nsf-prototype
  server:
    container_name: nsf-prototype-server 
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes: 
      - ./server:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: wget -qO- --no-verbose --tries=1 server:8000/health &> /dev/null || exit 1
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 1

    networks:
      - nsf-prototype

volumes:
  node_modules:
networks:
  nsf-prototype:
    driver: bridge
